Parameters:
  ProjectName:
    Type: String
    Description: "The name of the project for TaskCat deployment."

  PrivateSubnet1:
    Type: String
    Description: "The ID of the private subnet 1."

  PrivateSubnet2:
    Type: String
    Description: "The ID of the private subnet 2."

  PrivateInstanceSecurityGroup:
    Type: String
    Description: The ID of the security group for EKS.

  EKSClusterRoleArn:
    Type: String
    Description: The ARN of the IAM role for EKS.

  NodeInstanceRoleArn:
    Type: String
    Description: "The ARN of the IAM role for EC2 instances in the node group."

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub "${ProjectName}-eks-cluster"
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
        SecurityGroupIds:
          - !Ref PrivateInstanceSecurityGroup
      RoleArn: !Ref EKSClusterRoleArn
      KubernetesNetworkConfig:
        ServiceIpv4Cidr: 172.20.0.0/16 # A range of IP addresses allocated by Kubernetes for internal services exposed to other pods within the cluster but not directly to the internet.

  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster # Refers to the EKS cluster that the node group will join
      NodegroupName: !Sub "${ProjectName}-NodeGroup" # A name for the node group
      NodeRole: !Ref NodeInstanceRoleArn # IAM Role for EC2 instances
      Subnets:
        - !Ref PrivateSubnet1 # First private subnet
        - !Ref PrivateSubnet2 # Second private subnet
      ScalingConfig:
        DesiredSize: 2 # Initial number of EC2 instances
        MaxSize: 5 # Max number of EC2 instances in the node group
        MinSize: 1 # Min number of EC2 instances in the node group
      InstanceTypes:
        - t2.micro # EC2 instance type for the worker nodes
      AmiType: AL2_x86_64 # AMI type, e.g., Amazon Linux 2 (x86_64)

Outputs:
  EKSClusterName:
    Value: !Ref EKSCluster
    Description: "The name of the EKS cluster."

  NodeGroupName:
    Value: !Ref EKSNodeGroup
    Description: "The name of the EKS Node Group."
