project:
  name: lab2-21522490-taskcat-testing
  regions:
    - us-east-1
  s3_bucket: lab2-21522490-codepipeline-bucket

tests:
  mytest:
    template: ./module/parent_stack.yaml
    parameters:
      BucketName: lab2-21522490-codepipeline-bucket
      ProjectName: lab2-21522490-taskcat-testing
