project:
  name: final1-21522490
  regions:
    - us-east-1
  s3_bucket: final1-21522490-bucket

tests:
  mytest:
    template: ./modules/parent_stack.yaml
    parameters:
      ProjectName: final1-21522490
