
name: Deploy AWS Infrastructure with Terraform

on:
  push:
    branches:
      - main # Chỉ chạy workflow khi push lên nhánh main
  pull_request:
    branches:
      - main # Kiểm tra với pull request vào nhánh main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 4. Run Checkov to check security compliance
      - name: Install Checkov
        run: pip install checkov
      - name: Run Checkov
        run: checkov -d ./NT548_LAB/lab2/Terraform

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./NT548_LAB/lab2/Terraform

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./NT548_LAB/lab2/Terraform

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./NT548_LAB/lab2/Terraform

      # 8. Terraform Apply (chỉ chạy trên nhánh `main`)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ./NT548_LAB/lab2/Terraform
